<a href="https://colab.research.google.com/github/Tarun7386/DataScienceToolkit/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#The Pandas Series Object

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [ ]:
a=pd.Series({2:'a', 1:'b', 3:'c'})
a

2    a
1    b
3    c
dtype: object

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [ ]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [ ]:
states = pd.DataFrame({
    'population': population,
    'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
pd.DataFrame(population, columns=['population_data'])

population_data
California         38332521
Texas              26448193
New York           19651127
Florida            19552860
Illinois           12882135

In [ ]:
data = [{
       'a': i,
       'a^2': i * i}
        for i in range(2,6)]
ind = pd.Index(['A','B','C','D'])
# ind[1] = 'F' //immutable
df=pd.DataFrame(data,ind)
k=df.keys()
print(k)
df


Index(['a', 'a^2'], dtype='object')


a  a^2
A  2    4
B  3    9
C  4   16
D  5   25

In [ ]:
df1=list(df.items())
df1

[('a',
  A    2
  B    3
  C    4
  D    5
  Name: a, dtype: int64),
 ('a^2',
  A     4
  B     9
  C    16
  D    25
  Name: a^2, dtype: int64)]

In [ ]:
# ind1 = pd.Index([1, 3, 5, 7, 9])
# ind2 = pd.Index([2, 4, 6, 8, 10])
# a=ind1 & ind2 # intersection
# b=ind1 | ind2 # union
# c=ind1 ^ ind2 # symmetric difference
# print(a)
# print(b)
# print(c)

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
# slicing by explicit index
print(data)
data['a':'c']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


a    0.25
b    0.50
c    0.75
dtype: float64

In [ ]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [ ]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [ ]:
# fancy indexing
data[['a','b']]

a    0.25
b    0.50
dtype: float64

In [ ]:
data.loc['a']

0.25

In [ ]:
data.loc['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [ ]:
data.iloc[1:3]

b    0.50
c    0.75
dtype: float64

In [ ]:
a=np.array([[1,2,3,4],[4,1,2,4]])
print(a)

[[1 2 3 4]
 [4 1 2 4]]


In [ ]:
a.T

array([[1, 4],
       [2, 1],
       [3, 2],
       [4, 4]])

In [ ]:
df=pd.DataFrame(
    {
    'A':[1,2,3,4],
    'B':[5,6,7,8],
    'C':['a','b','c','d'],
    'D':['e','f','g','h'],
    'E':'i'
},index=['one','two','three','four'])
df

A  B  C  D  E
one    1  5  a  e  i
two    2  6  b  f  i
three  3  7  c  g  i
four   4  8  d  h  i

In [ ]:
df.loc['one':'three','A':'D']

A  B  C  D
one    1  5  a  e
two    2  6  b  f
three  3  7  c  g

In [ ]:
df.loc['one':'three',['A','D']]

A  D
one    1  e
two    2  f
three  3  g

In [ ]:
df.loc[['two','four'],['A','D']]

A  D
two   2  f
four  4  h

In [ ]:
df.iloc[1:3, :2]

A  B
two    2  6
three  3  7

In [ ]:
df[df.A>2]

A  B  C  D  E
three  3  7  c  g  i
four   4  8  d  h  i

#Ufuncs: Index Preservation

##**universal function - Ufuncs**

Preservation ensures that after applying a ufunc, the resulting array has the same shape and indexing as the original input arrays. This means if you perform an operation on two arrays of the same shape, the resulting array will also have the same shape,

In [ ]:
rng = np.random.RandomState(73)
ser = pd.Series(rng.randint(0, 12, 5))
a=pd.Series([2,4,9,16,25],index=['n1','n2','n3','n4','n5'])
ser


0     6
1     2
2    10
3     0
4     8
dtype: int64

In [ ]:
np.sqrt(ser)

0    2.449490
1    1.414214
2    3.162278
3    0.000000
4    2.828427
dtype: float64

In [ ]:
print(a)

n1     2
n2     4
n3     9
n4    16
n5    25
dtype: int64


In [ ]:
np.sqrt(a)

n1    1.414214
n2    2.000000
n3    3.000000
n4    4.000000
n5    5.000000
dtype: float64

In [ ]:
np.square(a)

n1      4
n2     16
n3     81
n4    256
n5    625
dtype: int64

In [ ]:
d=pd.DataFrame([np.sqrt(a),np.square(a)],index=['sqrt','square'])
d

n1    n2    n3     n4     n5
sqrt    1.414214   2.0   3.0    4.0    5.0
square  4.000000  16.0  81.0  256.0  625.0

##**UFuncs: Index Alignment**

In [ ]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'New York': 423967}, name='area')
population = pd.Series({'India': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')

In [ ]:
population / area

Alaska            NaN
India             NaN
New York    46.350605
Texas       38.018740
dtype: float64

In [ ]:
a=set(area.index) &set (population.index)
b=set(area.index) |set (population.index)
print(a)
print(b)


{'Texas', 'New York'}
{'New York', 'Texas', 'Alaska', 'India'}


In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
p=A * B
p

0     NaN
1     4.0
2    18.0
3     NaN
dtype: float64

In [ ]:
p.fillna('-')

0       -
1     4.0
2    18.0
3       -
dtype: object

In [ ]:
A.multiply(B, fill_value=0) #fills nan=0 and b adds to a

0     0.0
1     4.0
2    18.0
3     0.0
dtype: float64

+ add()
- sub(), subtract()
* mul(), multiply()
* / truediv(), div(), divide()
* // floordiv()
* % mod()
* pow()

##**Index alignment in DataFrame**

In [ ]:
A = pd.DataFrame(rng.randint(0, 20, (3, 3)),columns=list('ABC'))
A

A   B   C
0   9  14   3
1  18   4   3
2   1   7  15

In [ ]:
m1=pd.DataFrame({
    'A':[1,2,3,4],
    'B':[1,2,3,4],
    'C':[1,2,3,4],
    'D':[1,2,3,4],
},index=['one','two','three','four'])
m1


A  B  C  D
one    1  1  1  1
two    2  2  2  2
three  3  3  3  3
four   4  4  4  4

In [ ]:
m2=pd.DataFrame({
    'A':[5],
    'B':[6],
    'C':[7],
    'D':[8]
},index=['one','three','four','five'])
m2

A  B  C  D
one    5  6  7  8
three  5  6  7  8
four   5  6  7  8
five   5  6  7  8

In [ ]:
mm=m1*m2
mm

A     B     C     D
five    NaN   NaN   NaN   NaN
four   20.0  24.0  28.0  32.0
one     5.0   6.0   7.0   8.0
three  15.0  18.0  21.0  24.0
two     NaN   NaN   NaN   NaN

In [ ]:
mm.fillna('-')

A     B     C     D
five      -     -     -     -
four   20.0  24.0  28.0  32.0
one     5.0   6.0   7.0   8.0
three  15.0  18.0  21.0  24.0
two       -     -     -     -

## **Ufuncs: Operations Between DataFrame and Series**

In [ ]:
# A = rng.randint(10, size=(3, 4))
# A
A=np.array([[1, 2, 3, 4],
       [1, 2, 2, 1],
       [3, 1, 2, 0]])
A

array([[1, 2, 3, 4],
       [1, 2, 2, 1],
       [3, 1, 2, 0]])

In [ ]:
print(A[0])
A - A[0]

[1 2 3 4]


array([[ 0,  0,  0,  0],
       [ 0,  0, -1, -3],
       [ 2, -1, -1, -4]])

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0  0 -1 -3
2  2 -1 -1 -4

In [ ]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -1  0  1  2
1 -1  0  0 -1
2  2  0  1 -1

##**Handling Missing Data**

| Typeclass | Conversion when storing NAs | NA sentinel value |
|-----------|------------------------------|-------------------|
| floating  | No change                    | np.nan            |
| object    | No change                    | None or np.nan    |
| integer   | Cast to float64              | np.nan            |
| boolean   | Cast to object               | None or np.nan    |


In [ ]:
vals2 = np.array([1, np.nan, 3, 4])
print(vals2.dtype)
vals2.sum(), vals2.min(), vals2.max()

float64


(nan, nan, nan)

In [ ]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [ ]:
a=pd.Series([1, np.nan, 2, None])
a.dtype

dtype('float64')

In [ ]:
vals1 = np.array([1, None, 3, 4])
print(vals1.dtype)

object


In [ ]:
x = pd.Series(range(2), dtype=int)
print(x.dtype,"\n^^")
x[0] = None
print(x.dtype)

int64 
^^
float64


##**Operating on Null Values**

In [ ]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [ ]:
print(data)
print()
data.dropna()

0        1
1      NaN
2    hello
3     None
dtype: object



0        1
2    hello
dtype: object

In [ ]:
df = pd.DataFrame([[1, np.nan, 2],[2, 3, 5],[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [ ]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [ ]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.dropna(axis='columns', how='all') # remove all na columns

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6


0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.loc[len(df)]=[None,None,None]
print(df)
df.dropna(how='all')

     0    1     2
0  1.0  NaN     2
1  2.0  3.0     5
2  NaN  4.0     6
3  NaN  NaN  None


0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df

0    1     2
0  1.0  NaN     2
1  2.0  3.0     5
2  NaN  4.0     6
3  NaN  NaN  None

In [ ]:
df.dropna(axis='rows', thresh=3) # remove (thresh) with 3 or more na's in  rows

0    1  2
1  2.0  3.0  5

## **Filling null values**

In [ ]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
df_fill=data.fillna('-')
df_fill

a    1.0
b      -
c    2.0
d      -
e    3.0
dtype: object

***forward-fill to propagate the previous value forward***

In [ ]:
print(df_fill)
print()
data.fillna(method='ffill')

a    1.0
b      -
c    2.0
d      -
e    3.0
dtype: object



a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

***a back-fill to propagate the next values backward***

In [ ]:
print(df_fill)
print()
data.fillna(method='bfill')

a    1.0
b      -
c    2.0
d      -
e    3.0
dtype: object



a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

# **Hierarchical Indexing**

## ***A Multiply Indexed Series***

In [ ]:
s=[1,2,3,4,5]
index=[('a','b'),('c','d'),('e','f'),('g','h'),('i','j')]
a=pd.Series(s,index=index)
a

(a, b)    1
(c, d)    2
(e, f)    3
(g, h)    4
(i, j)    5
dtype: int64

In [ ]:
a[('a','b'):('e','f')]

(a, b)    1
(c, d)    2
(e, f)    3
dtype: int64

In [ ]:
index = pd.MultiIndex.from_tuples(index)
print(index)
p=a.reindex(index)
p

MultiIndex([('a', 'b'),
            ('c', 'd'),
            ('e', 'f'),
            ('g', 'h'),
            ('i', 'j')],
           )


a  b    1
c  d    2
e  f    3
g  h    4
i  j    5
dtype: int64

In [ ]:
p_df = p.unstack()
p_df

b    d    f    h    j
a  1.0  NaN  NaN  NaN  NaN
c  NaN  2.0  NaN  NaN  NaN
e  NaN  NaN  3.0  NaN  NaN
g  NaN  NaN  NaN  4.0  NaN
i  NaN  NaN  NaN  NaN  5.0

In [ ]:
p_df.stack()

a  b    1.0
c  d    2.0
e  f    3.0
g  h    4.0
i  j    5.0
dtype: float64

In [ ]:
df = pd.DataFrame(
    [[5,4,3,2,1],
     [6,5,4,3,2],
     [9,8,7,6,5],
     [5,4,3,2,1]],
    index=[['a','a','b','b'],[1,2,1,2]],
    columns=['A', 'B', 'C', 'D', 'E']
)
print(df) # stack
df.unstack()


     A  B  C  D  E
a 1  5  4  3  2  1
  2  6  5  4  3  2
b 1  9  8  7  6  5
  2  5  4  3  2  1


A     B     C     D     E   
   1  2  1  2  1  2  1  2  1  2
a  5  6  4  5  3  4  2  3  1  2
b  9  5  8  4  7  3  6  2  5  1

In [ ]:
index=pd.MultiIndex.from_product([['Tar','bhanu','cheri'],[2,1]])
columns=pd.MultiIndex.from_product([['Sem1','Sem2','Sem3'],['subject1','subject2']])
df=pd.DataFrame(np.random.rand(6,6),index=index,columns=columns)
df

Sem1                Sem2                Sem3          
         subject1  subject2  subject1  subject2  subject1  subject2
Tar   2  0.611547  0.972599  0.879684  0.441593  0.486102  0.987617
      1  0.047389  0.369578  0.394381  0.425142  0.038762  0.831245
bhanu 2  0.902350  0.468104  0.186864  0.158006  0.645385  0.288902
      1  0.634035  0.696272  0.038396  0.468190  0.599158  0.896945
cheri 2  0.366589  0.249584  0.704412  0.516141  0.256051  0.714759
      1  0.822948  0.240525  0.888015  0.702280  0.441911  0.532725

In [ ]:
df['Sem2']

subject1  subject2
Tar   2  0.879684  0.441593
      1  0.394381  0.425142
bhanu 2  0.186864  0.158006
      1  0.038396  0.468190
cheri 2  0.704412  0.516141
      1  0.888015  0.702280

In [ ]:
ao=df['Sem2','subject2']
ao

Tar    2    0.441593
       1    0.425142
bhanu  2    0.158006
       1    0.468190
cheri  2    0.516141
       1    0.702280
Name: (Sem2, subject2), dtype: float64

In [ ]:
df.index.names = ['names', 'ranks']
df

Sem1                Sem2                Sem3          
             subject1  subject2  subject1  subject2  subject1  subject2
names ranks                                                            
Tar   2      0.611547  0.972599  0.879684  0.441593  0.486102  0.987617
      1      0.047389  0.369578  0.394381  0.425142  0.038762  0.831245
bhanu 2      0.902350  0.468104  0.186864  0.158006  0.645385  0.288902
      1      0.634035  0.696272  0.038396  0.468190  0.599158  0.896945
cheri 2      0.366589  0.249584  0.704412  0.516141  0.256051  0.714759
      1      0.822948  0.240525  0.888015  0.702280  0.441911  0.532725

In [ ]:
df1 = df.sort_index()
df1


Sem1                Sem2                Sem3          
             subject1  subject2  subject1  subject2  subject1  subject2
names ranks                                                            
Tar   1      0.047389  0.369578  0.394381  0.425142  0.038762  0.831245
      2      0.611547  0.972599  0.879684  0.441593  0.486102  0.987617
bhanu 1      0.634035  0.696272  0.038396  0.468190  0.599158  0.896945
      2      0.902350  0.468104  0.186864  0.158006  0.645385  0.288902
cheri 1      0.822948  0.240525  0.888015  0.702280  0.441911  0.532725
      2      0.366589  0.249584  0.704412  0.516141  0.256051  0.714759

In [ ]:
# reset_index,set_index data aggregation methods, such as mean(), sum(), and count()

#Combining Datasets: Concat and Append

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = [[1, 2],
    [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [ ]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

In [ ]:
df1 = pd.DataFrame([[1, 2],[2,1,]],columns=['A','B'],index=['a','b'])
df2 = pd.DataFrame([[3, 4],[2,1]],columns=['A','B'],index=['c','d'])
print(df1);
print(df2);


   A  B
a  1  2
b  2  1
   A  B
c  3  4
d  2  1


***Adding MultiIndex keys.***

In [ ]:
s=pd.concat([df1, df2],keys=['B','T'])
s

A  B
B a  1  2
  b  2  1
T c  3  4
  d  2  1

***Concatenation with joins***

In [ ]:
df3 = pd.DataFrame([[1, 3],[2,1,]],columns=['A','B'],index=['a','b'])
df4 = pd.DataFrame([[3, 4],[2,4]],columns=['C','A'],index=['c','d'])
print(df3)
print(df4)


   A  B
a  1  3
b  2  1
   C  A
c  3  4
d  2  4


In [ ]:
print(pd.concat([df3, df4], join='inner')) # by default outer

   A
a  1
b  2
c  4
d  4


***Merge and Join***

The pd.merge() function implements a number of types of joins: the
* one-to-one,
* many-to-one, and
* many-to-many joins.
All three types of joins are accessed by
identical call --> pd.merge()

###One-to-one joins

In [ ]:
df1 = pd.DataFrame({
    'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']
    })
df2 = pd.DataFrame({
    'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
    'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [ ]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
df4 = pd.concat([df1, df2])
df4

employee        group  hire_date
0      Bob   Accounting        NaN
1     Jake  Engineering        NaN
2     Lisa  Engineering        NaN
3      Sue           HR        NaN
0     Lisa          NaN     2004.0
1      Bob          NaN     2008.0
2     Jake          NaN     2012.0
3      Sue          NaN     2014.0

###*Many-to-one joins*

In [ ]:
df5 = pd.DataFrame({
    'group': ['Accounting', 'Accounting',
    'Engineering', 'Engineering',
    'HR', 'HR'],'skills': ['math', 'spreadsheets', 'coding', 'linux',
     'spreadsheets', 'organization']})
print(pd.merge(df1, df5))

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


***Specification of the Merge Key***

In [ ]:
print(pd.merge(df1, df2, on='employee'))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [ ]:
df3 = pd.DataFrame({
    'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'salary': [70000, 80000, 120000, 90000]
    })
print(pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


In [ ]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [ ]:
# print(pd.merge(df1, df3,on="employee",suffixes=["_L", "_R"]))

##**Aggregation and Grouping**

| Aggregation       | Description                       |
|-------------------|-----------------------------------|
| count()           | Total number of items             |
| first(), last()   | First and last item               |
| mean(), median()  | Mean and median                   |
| min(), max()      | Minimum and maximum               |
| std(), var()      | Standard deviation and variance   |
| mad()             | Mean absolute deviation           |
| prod()            | Product of all items              |
| sum()             | Sum of all items                  |


In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [ ]:
ser.sum()

2.811925491708157

In [ ]:
ser.mean()

0.5623850983416314

In [ ]:
ser.min()

0.15601864044243652

###***GroupBy: Split, Apply, Combine***

In [ ]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [ ]:
a=df.groupby('key')
a.sum()

data
key      
A       3
B       5
C       7

Aggregate, filter, transform, apply

aggregate() method allows for even more flexibility. It can take
a string, a function, or a list there of, and ***compute all the aggregates at once.with sum(), median(),***

In [ ]:
df.groupby('key').aggregate(['min', np.median, max])

data           
     min median max
key                
A      0    1.5   3
B      1    2.5   4
C      2    3.5   5

#***Pivot Tables***

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
import pandas as pd

# Sample data
data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-01', '2023-01-02', '2023-01-03'],
    'Category': ['A', 'A', 'A', 'B', 'B', 'B'],
    'Value': [10, 15, 10, 20, 25, 20]
}

df = pd.DataFrame(data)

# Create a single-level pivot table
pivot_table = pd.pivot_table(df, values='Value', index='Date', columns='Category', aggfunc='sum')

print("Single-Level Pivot Table:")
pivot_table


Single-Level Pivot Table:


Category     A   B
Date              
2023-01-01  10  20
2023-01-02  15  25
2023-01-03  10  20

#**Vectorized String Operations**

In [ ]:
data = ['peter', 'Paul', 'MARY', 'gUIDO']
names = pd.Series(data)
names

0    peter
1     Paul
2     MARY
3    gUIDO
dtype: object

In [ ]:
names.str.capitalize()

0    Peter
1     Paul
2     Mary
3    Guido
dtype: object

| Method        |
|---------------|
| len()         |
| lower()       |
| islower()     |
| ljust()       |
| upper()       |
| startswith()  |
| isupper()     |
| find()        |
| endswith()    |
| isnumeric()   |
| isalnum()     |
| isdecimal()   |
| index()       |
| isalpha()     |
| split()       |
| strip()       |
| rindex()      |
| isdigit()     |
| rsplit()      |
| rstrip()      |
| capitalize()  |     
| swapcase()    |
| istitle()     |



##**Working with Time Series**

In [ ]:
import numpy as np
date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

In [ ]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04',
'2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [ ]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range('2015-07-03', periods=8, freq='H')

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')

In [ ]:
pd.date_range('2015-07-03', periods=8, freq='M')

DatetimeIndex(['2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31',
               '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29'],
              dtype='datetime64[ns]', freq='M')

In [ ]:
pd.timedelta_range(0, periods=10, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='H')

#**High-Performance Pandas: eval() and query()**

In [ ]:
df1=pd.DataFrame(np.random.randn(5, 4))
df2=pd.DataFrame(np.random.randn(5, 4))
df3=pd.DataFrame(np.random.randn(5, 4))
df4=pd.DataFrame(np.random.randn(5, 4))
df5=pd.DataFrame(np.random.randn(5, 4))


In [ ]:
result1 = -df1 * df2 / (df3 + df4) - df5
result2 = pd.eval('-df1 * df2 / (df3 + df4) - df5')
np.allclose(result1, result2)

True

In [ ]:
rng= np.random.RandomState(42)
df1,df2 = (pd.DataFrame(rng.randint(0,1000,(100,3)))for i in range(2))
r1=df1*df2
r2=pd.eval('df1*df2')
np.allclose(r1,r2)


True

In [ ]:
df = pd.DataFrame(rng.rand(1000, 3), columns=['A', 'B', 'C'])
df.head()
result1 = df[(df.A < 0.5) & (df.B < 0.5)]
result2 = df.query('A < 0.5 and B < 0.5')
np.allclose(result1, result2)

True