<a href="https://colab.research.google.com/github/Tarun7386/DataScienceToolkit/blob/main/Numpy/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
# https://numpy.org/
import numpy as np
np.__version__

'1.25.2'

In [ ]:
import numpy as np
arr=np.array([1,7,3,4,5])
arr

array([1, 7, 3, 4, 5])

***Difference between numpy array and list***

- Data type should be same of all the elements in a numpy array whereas it can be different in case of lists.
- **Broadcasting:** https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [ ]:
np.broadcast
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
print(a + b)
b = np.array([1.0, 2.0, 3.0, 4.0])
# a + b gets error

[2. 4. 6.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


**If we add an element of string data type in a numpy array then it will upcast the data type to string of all the elements.**

In [ ]:
print(np.array([1, 4, 2, '5', 3, False]))
print(np.array([1, 4, 2,  3, False]))

['1' '4' '2' '5' '3' 'False']
[1 4 2 3 0]


In [ ]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
b = np.array(a)
print("matrix")
print(b)
print("array :",a)

matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
a=np.random.randint(0, 10, (3, 3))
np.random.seed(0) # seed for reproducibility i.e. Same values will be generated
print(a)

[[5 0 3]
 [3 7 9]
 [3 5 2]]


***Create a matrix of `Zeros` & `Ones` of specific dimension.***

In [ ]:
a=np.zeros(5,dtype=int)
print(a)
b=np.zeros((3,3),dtype=float)
b

[0 0 0 0 0]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c=np.ones((3,4),dtype=int)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.identity(3, dtype=int) # np.eye(3,dtype=int)
#np.empty(3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
a=np.full((3,3), 3)
b=np.full((3,3),70)
b

array([[70, 70, 70],
       [70, 70, 70],
       [70, 70, 70]])



---
***Array Concatenation :***

---

In [ ]:
d=np.concatenate([a,b],axis=0) # Concatenate Row wise
e=np.concatenate([a,b],axis=1) # Concatenate coloumn wise
d,e

(array([[ 3,  3,  3],
        [ 3,  3,  3],
        [ 3,  3,  3],
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]]),
 array([[ 3,  3,  3, 70, 70, 70],
        [ 3,  3,  3, 70, 70, 70],
        [ 3,  3,  3, 70, 70, 70]]))

 https://numpy.org/doc/1.17/user/index.html


In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)|
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)|
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)|
| ``int8``      | Byte (-128 to 127)|
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)|
| ``uint8``     | Unsigned integer (0 to 255)|
| ``uint16``    | Unsigned integer (0 to 65535)|
| ``uint32``    | Unsigned integer (0 to 4294967295)|
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)|
| ``float_``    | Shorthand for ``float64``.|
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| ``complex_``  | Shorthand for ``complex128``.|
| ``complex64`` | Complex number, represented by two 32-bit floats|
| ``complex128``| Complex number, represented by two 64-bit floats|

In [ ]:
x2 = np.random.randint(50, size=(2,3,4)) #(depth,row,col)
np.random.seed(0)
x2

array([[[44, 47,  0,  3],
        [ 3, 39,  9, 19],
        [21, 36, 23,  6]],

       [[24, 24, 12,  1],
        [38, 39, 23, 46],
        [24, 17, 37, 25]]])

In [ ]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes 24*8:", x2.nbytes, "bytes")

x2 ndim:  3
x2 shape: (2, 3, 4)
x2 size:  24
itemsize: 8 bytes
nbytes 24*8: 192 bytes


**Slicing**

In [ ]:
x= np.arange(10)
print(x)
print(x[1::2])  # every other element, starting at index 1
print(x[::-1])  # all elements, reversed
print(x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [ ]:
y=np.random.randint(10,size=(3,3))
print(y)
print()
print(y[:2, :3])  # two rows, three columns
print()
print(y[0:,::-1])
print()
print(y[1::-1, ::-2])
print(y[:, 0])
z=y[:2,:2].copy()
z

[[1 6 8]
 [8 3 2]
 [3 6 3]]

[[1 6 8]
 [8 3 2]]

[[8 6 1]
 [2 3 8]
 [3 6 3]]

[[2 8]
 [8 1]]
[1 8 3]


array([[1, 6],
       [8, 3]])

**Reshaping of Arrays**

In [ ]:
grid = np.arange(0, 12).reshape((3, 4))
print(grid)
x = np.array([1, 2, 3])
print(x)
# row vector via reshape
a=x.reshape((1, 3))
print(a)
grid.shape


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3]
[[1 2 3]]


(3, 4)

**For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:**

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
y=np.array([[73],[74]])
np.hstack([grid,y])

array([[ 9,  8,  7, 73],
       [ 6,  5,  4, 74]])

In [ ]:
import numpy as np
a=np.random.randint(25,size=(2,3,4))
b=np.random.randint(50,size=(2,3,4))
np.random.seed(0)
# print(a)
# print(b)
print()
c=np.dstack([a,b])
print(c)


[[[12 15 21  0 37 25 13  8]
  [ 3  3  7  9  9 20 16  5]
  [19 21 18  4 15 47  0 18]]

 [[23  6 24 24 35 24 49 29]
  [12  1  6  7 19 19 14 39]
  [23 14 24 17 32  1  9 32]]]


#Splitting of arrays



**The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:**

In [ ]:
import numpy as np
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3, x4 = np.split(x, [3, 5, 7])
print(x1, x2, x3, x4)

[1 2 3] [99 99] [3 2] [1]


In [ ]:
import numpy as np
b=np.random.randint(50,size=(4,5))
np.random.seed(0)
print(b)
upper,lower=np.vsplit(b,[2])
print("<---------Vsplit------->\n")
print("--------UPPER-------------------")
print(upper)
print("--------LOWER-------------------")
print(lower)
print()
print("<---------Hsplit------->\n")
left,right=np.hsplit(b,[2])
print("--------LEFT-------------------")
print(left)
print("--------RIGHT-------------------")
print(right)


[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
<---------Vsplit------->

--------UPPER-------------------
[[44 47  0  3  3]
 [39  9 19 21 36]]
--------LOWER-------------------
[[23  6 24 24 12]
 [ 1 38 39 23 46]]

<---------Hsplit------->

--------LEFT-------------------
[[44 47]
 [39  9]
 [23  6]
 [ 1 38]]
--------RIGHT-------------------
[[ 0  3  3]
 [19 21 36]
 [24 24 12]
 [39 23 46]]


# Computation on NumPy Arrays: Universal Functions

In [ ]:
import math
x=9
y=math.sqrt(x)
print(y)

3.0


In [ ]:
import numpy as np
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [ ]:
print(np.pi)
theta = np.linspace(0, np.pi, 3)
print(theta)

3.141592653589793
[0.         1.57079633 3.14159265]


In [ ]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
print(np.sin(90))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
0.8939966636005579


In [ ]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
