<a href="https://colab.research.google.com/github/Tarun7386/DataScienceToolkit/blob/main/Numpy/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [ ]:
dtype=np.dtype({'names':('name', 'age', 'weight'),
'formats':('U10', 'i4', 'f8')})

In [ ]:
data = np.array([('Alice',25,55.0),('Bob',45,85.5),('Cathy',37,68.0),('Doug',19,61.5)], dtype=dtype)
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [ ]:
data_record=data.view(np.recarray)
data_record.age

array([25, 45, 37, 19], dtype=int32)

# **Sorting**

In [ ]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
x.sort()
print(x)

[1 2 3 4 5]


In [ ]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [ ]:
np.random.seed(42)
X = np.random.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [ ]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [ ]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# **Partial Sorts: Partitioning**

In [ ]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [ ]:
np.partition(X, 4, axis=1)

array([[6, 6, 3, 4, 7, 9],
       [3, 2, 6, 4, 7, 7],
       [1, 5, 2, 4, 7, 7],
       [0, 4, 1, 5, 5, 9]])

# **Fancy Indexing**

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [ ]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [ ]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [ ]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


Masking

In [ ]:
import numpy as np

# Set the random seed for NumPy
np.random.seed(42)

# Generate a 4x6 array with random integers between 0 and 10
X = np.random.randint(0, 10, (4, 6))

# Print the generated array
print("Array X:")
print(X)

# Create a mask for elements greater than 5
mask = X > 5

# Print the mask
print("\nMask (X > 5):")
print(mask)

# Use the mask to extract elements that satisfy the condition
masked_elements = X[mask]

# Print the elements that satisfy the condition
print("\nElements greater than 5:")
print(masked_elements)


Array X:
[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]

Mask (X > 5):
[[ True False  True False  True  True]
 [False  True  True False False  True]
 [ True False False False False  True]
 [False False False False  True False]]

Elements greater than 5:
[6 7 6 9 6 7 7 7 7 9]


# **Computation on Arrays: Broadcasting**

Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction
between the two arrays:
* Rule 1: If the two arrays differ in their number of dimensions, the shape of the
one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array
with shape equal to 1 in that dimension is stretched to match the other shape.
*Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is
raised.

In [ ]:
M = np.ones((2, 3))
a = np.arange(3)
print(M.shape)
print(a.shape)

(2, 3)
(3,)


In [ ]:
(M+a).shape # rule 2

(2, 3)

M.shape -> (2, 3)
a.shape -> (1, 3)

M.shape -> (2, 3)
a.shape -> (2, 3)

In [ ]:
c = np.arange(3).reshape((3, 1))
b = np.arange(3)
c.shape,b.shape

((3, 1), (3,))

In [ ]:
(c+b).shape

(3, 3)